# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('eMail', models.EmailField(max_length=200)),
                ('Password', models.TextField()),
            ],
        ),
    ]
