# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 23:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20171201_0451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='person',
        ),
        migrations.RemoveField(
            model_name='person',
            name='massage',
        ),
        migrations.AddField(
            model_name='conversation',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.Person'),
        ),
    ]
