# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 23:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_auto_20171201_0545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='name',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='type',
        ),
    ]
