# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 19:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_db', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='roll',
        ),
    ]
