# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '__first__'),
        ('test_db', '0002_auto_20171222_0119'),
    ]

    operations = [
        migrations.CreateModel(
            name='applicent',
            fields=[
                ('applicant_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='applicant.Applicant')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('applicant.applicant',),
        ),
    ]
